builds:
  - binary: emlx
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  -
    wrap_in_directory: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

brews:
  -
    github:
      owner: leighmcculloch
      name: emlx
    folder: Formula
    homepage: "https://github.com/leighmcculloch/emlx"
    description: Email file (.eml) attachment and embedded file extractor.
    test: |
      system "#{bin}/emlx"
    install: |
      bin.install "emlx"
