# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Emlx < Formula
  desc "Email file (.eml) attachment and embedded file extractor."
  homepage "https://github.com/leighmcculloch/emlx"
  version "1.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leighmcculloch/emlx/releases/download/v1.0.1/emlx_1.0.1_darwin_amd64.tar.gz"
      sha256 "b02dd69416ec2ea080bcd5de5411462b0d7f20595a4ca931258c948710598665"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/leighmcculloch/emlx/releases/download/v1.0.1/emlx_1.0.1_linux_amd64.tar.gz"
      sha256 "15443856d1fa10879e1cb2f3c354e8299a4bc339a6c46b1e43bf8c74d67106dd"
    end
  end

  def install
    bin.install "emlx"
  end

  test do
    system "#{bin}/emlx"
  end
end
